<?xml version="1.0" encoding="utf-8"?><Database Name="al" Class="MISDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.84\S1;Initial Catalog=al;Persist Security Info=True;User ID=sa" SettingsObjectName="ClinicSystem.My.MySettings" SettingsPropertyName="alConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.log_Adm" Member="log_Adm">
    <Type Name="log_Adm">
      <Column Name="access_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="regdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="application_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="machine_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ip_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="userid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="operation_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.log_Err" Member="log_Err">
    <Type Name="log_Err">
      <Column Name="error_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="error_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="application_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="machine_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ip_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="userid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="error_message" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_opd" Member="tbl_opd">
    <Type Name="tbl_opd">
      <Column Name="CASENO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SDATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="VIST" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RMNO" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="uid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DEPTNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOCTNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="POSINAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HEATH_CARD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ICDCODE1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ICDCODE2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ICDCODE3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="INS_CODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STEXT" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OTEXT" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Pijia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="t3" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="d1" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="d2" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_opd_order" Member="tbl_opd_order">
    <Type Name="tbl_opd_order">
      <Column Name="CASENO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="uid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="OD_idx" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TIMES_DAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="METHOD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TIME_QTY1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DAYS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BILL_QTY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRICE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CLASS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CHRONIC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.xml_ddata" Member="xml_ddata">
    <Type Name="xml_ddata">
      <Column Name="t3" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="d1" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="d2" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="d3" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="d4" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="d8" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="d9" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="d11" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="d14" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="d15" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="d16" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="d17" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="d18" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="d19" Type="System.String" DbType="NChar(9)" CanBeNull="true" />
      <Column Name="d20" Type="System.String" DbType="NChar(9)" CanBeNull="true" />
      <Column Name="d21" Type="System.String" DbType="NChar(9)" CanBeNull="true" />
      <Column Name="d22" Type="System.String" DbType="NChar(9)" CanBeNull="true" />
      <Column Name="d23" Type="System.String" DbType="NChar(9)" CanBeNull="true" />
      <Column Name="d27" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d28" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="d29" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Column Name="d30" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="d32" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d33" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d34" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d35" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="d36" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d38" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d39" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d40" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d41" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="d49" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.xml_tdata" Member="xml_tdata">
    <Type Name="xml_tdata">
      <Column Name="t1" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="t2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="t3" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="t4" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="t5" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="t6" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="t37" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="t38" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="t39" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="t40" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="t41" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="t42" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.xml_pdata" Member="xml_pdata">
    <Type Name="xml_pdata">
      <Column Name="t3" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="d1" Type="System.String" DbType="NChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="d2" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="p1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="p2" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="p3" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="p4" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="p5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="p6" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
      <Column Name="p7" Type="System.String" DbType="NChar(18)" CanBeNull="true" />
      <Column Name="p8" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="p9" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Column Name="p10" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="p11" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="p12" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="p13" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="p14" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="p15" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="p16" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="p17" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="p20" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_lab" Member="tbl_lab">
    <Type Name="tbl_lab">
      <Column Name="uid" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lid" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="mf" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="cid" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="l01" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="l02" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="l03" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l04" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="l05" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="l06" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_lab_record" Member="tbl_lab_record">
    <Type Name="tbl_lab_record">
      <Column Name="uid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lid" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="l05" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="iid" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="l07" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l09" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CASENO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OD_idx" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.p_lab_temp" Member="p_lab_temp">
    <Type Name="p_lab_temp">
      <Column Name="temp_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="l05" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="iid" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="l08" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="l10" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="l11" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_patients" Member="tbl_patients">
    <Type Name="tbl_patients">
      <Column Name="cid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="uid" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mf" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="bd" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="p01" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="p02" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="p03" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="p04" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.p_order" Member="p_order">
    <Type Name="p_order">
      <Column Name="rid" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="r01" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r02" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r03" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r04" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r06" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r07" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r08" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r09" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r10" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r11" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r12" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r13" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r14" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r15" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r16" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r18" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r19" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r25" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r26" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r27" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r28" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r29" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r30" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r31" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r32" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r33" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r34" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r40" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r48" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="r52" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="r60" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="r61" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="r62" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_pijia" Member="tbl_pijia">
    <Type Name="tbl_pijia">
      <Column Name="YM" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STATUS" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="bid" Type="System.String" DbType="Char(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="op" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VDATE" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="SDATE" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="VIST" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="RMNO" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DEPTNAME" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="DOCTNAME" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="POSINAME" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HEATH_CARD" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Youmian" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="PAYNO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="uid" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MedFee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegFee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Copay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deposit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SelfPay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PharmW" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Arrears" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AMTreceivable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AMTreceived" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bremark" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CASENO" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="G" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_labdata_not_match_with_opd_order" Member="v_labdata_not_match_with_opd_order">
    <Type Name="v_labdata_not_match_with_opd_order">
      <Column Name="lid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="uid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l05" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="iid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nhi_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l07" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l09" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l08" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_opdorder_not_match_with_lab_record" Member="v_opdorder_not_match_with_lab_record">
    <Type Name="v_opdorder_not_match_with_lab_record">
      <Column Name="CASENO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="uid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="OD_idx" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="rid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="l08" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_change_dep" Method="sp_change_dep">
    <Parameter Name="YM" Parameter="yM" Type="System.String" DbType="Char(5)" />
    <ElementType Name="sp_change_depResult">
      <Column Name="o" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_hdata" Method="sp_get_hdata">
    <Parameter Name="ym" Type="System.String" DbType="NVarChar(5)" />
    <ElementType Name="sp_get_hdataResult">
      <Column Name="h1" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="h2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="h3" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="h4" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="h5" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="h6" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="h7" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="h8" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="h9" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="h10" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="h11" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="h17" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="h18" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="h19" Type="System.String" DbType="NChar(13)" CanBeNull="true" />
      <Column Name="h20" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="h22" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="h23" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="h25" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="h26" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="r1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="r2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="r3" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="r4" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="r5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="r6a" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="r6b" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="r9" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="r10" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_match_xml" Method="sp_match_xml">
    <ElementType Name="sp_match_xmlResult">
      <Column Name="rows_affected" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CASENO_for_pijia" Method="sp_CASENO_for_pijia">
    <ElementType Name="sp_CASENO_for_pijiaResult">
      <Column Name="rows_affected" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PIJIA_for_opd" Method="sp_PIJIA_for_opd">
    <ElementType Name="sp_PIJIA_for_opdResult">
      <Column Name="CASENO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDATE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VIST" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RMNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_match_lab" Method="sp_match_lab">
    <Parameter Name="f" Type="System.Int32" DbType="Int" />
    <Parameter Name="t" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_match_labResult">
      <Column Name="rows_affected" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>